#!/bin/bash
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=4:mem=10gb
#PBS -N pipest_test

echo "I am submitting $script_name"

module load anaconda3/personal
source activate h_impact_env

cd $PBS_O_WORKDIR
python "$script_name"

conda deactivate
